config/routes.rb
Newaperio11::Application.routes.draw do
  devise_for :authors, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	get 'about' => 'static#about', :as => :about
	get 'portfolio' => 'static#portfolio', :as => :portfolio
	get 'contact' => 'static#contact', :as => :contact
	resources :blog, :as => "post", :controller => "posts", :only => [:index, :show] do
	  collection do
	    get "search"
	    get "category/:id" => "posts#category", :as => :category
	    get "feed(.:format)" => "posts#feed", :as => :feed, :defaults => { :format => 'atom' }
	  end
	end
	root :to => "static#home"
end

app/models/author.rb
class Author < ActiveRecord::Base
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

	has_many :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  
	def to_param
    "#{name.downcase.gsub(/[^[:alnum:]]/,'-')}".gsub(/-{2,}/,'-')
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :author
	belongs_to :category
	belongs_to :post_type

	validates :title, :content, :author_id, :category_id, :post_type_id, :presence => true
	
	after_create :campfire, :if => Proc.new { |p| Rails.env.production? }
		
	def to_param
    "#{id}-#{title.downcase.gsub(/[[:punct:]]/,'').gsub(/[^[:alnum:]]/,'-')}".strip.gsub(/-{2,}/,'-')
  end 

  def self.front_end_search(query)
    where(front_end_search_conditions(query))
  end
  
  private
  
  def campfire
    begin
      campfire = Tinder::Campfire.new('newaperio',:token => '4ff664abcb2ea9663ded0fc8674b0ac6a715b46d')
      room = campfire.find_room_by_name("the Lyceum")
      room.speak("#{self.author.name} just posted \"#{self.title}\". Read it now: http://newaperio.com/blog/#{self.to_param}.")
	  rescue => e
	   Rails.logger.debug { "Error posting notification to campfire." }
	  end
  end
  
  def self.front_end_search_conditions(query)
    query.split(/\s+/).map do |word|
      '(' + %w[title content].map { |col| "#{col} LIKE #{sanitize('%' + word.to_s + '%')}" }.join(' OR ') + ')'
    end.join(' AND ')
  end
end

app/models/post_type.rb
class PostType < ActiveRecord::Base
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
		@posts = Post.order("created_at DESC").page(params[:page]).per(10)
  end

  def show
		@post = Post.find(params[:id])
  end

	def search
		@posts = Post.front_end_search(params[:term]).order("created_at DESC").page(params[:page]).per(10)
	end
	
	def category
		@category = Category.find_by_name(params[:id])
		@posts = Post.where("category_id = ?",@category.id).order("created_at DESC").page(params[:page]).per(10)
	end
	
	def feed
	  @posts = Post.order("created_at DESC").limit(20) 
	  respond_to do |format|
      format.atom { render :layout => false }
      format.rss { redirect_to feed_post_index_url("atom"), :status => :moved_permanently }
	  end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	  author = Author.authenticate(params[:email], params[:password])
	  if author
	    session[:author_id] = author.id
	    redirect_to blog_admin_index_path, :notice => "Logged in!"
	  else
	    flash[:notice] = "Invalid email or password."
	    render "new"
	  end
	end

	def destroy
	  session[:author_id] = nil
	  redirect_to login_path, :notice => "Logged out!"
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
		@posts = Post.order("created_at desc").where("post_type_id = ?",1).limit(3)
  end

  def about
  end

  def portfolio
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def textilize(text)
    CodeFormatter.new(text).to_html.html_safe unless text.blank?
  end
  
  def title(page_title)
    content_for(:title) { page_title }
  end
  
  def render_post_type(post, single = false)
    post_type = post.post_type.name.downcase    
    unless post_type == "post" || post_type == "chat" || post_type == "video"
      post_type = "post"
    end
    render :partial => "posts/#{post_type}", :locals => {:post => post, :single => single}
  end
  
  def is_staff(name, email)
    case name
    when "Logan Leger"
      " staff" if email == "logan@newaperio.com"
    when "Jonathan Hooper"
      " staff" if email == "jonathan@newaperio.com"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_ga.html.erb
<script>
  var _gaq=[['_setAccount','UA-15433099-1'],['_trackPageview'],['_trackPageLoadTime']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

app/views/layouts/_sidebar.html.erb
<p>This cleverly titled blog is authored by NewAperio, a web and mobile development collective in Baton Rouge. We write about programming, design and entrepreneurship. Read more <%= link_to "about us", about_path %>.</p>

<p>To keep up, <a href="http://twitter.com/newaperio" title="Follow NewAperio on Twitter">follow us on Twitter</a>, <a href="http://facebook.com/newaperio" title="Like NewAperio on Facebook">like us on Facebook</a> or <%= link_to "subscribe via RSS", feed_post_index_path("rss") %>.</p>

<h3>Categories</h3>
<ul>
  <% for category in Category.all %>
    <li><%= link_to category.name, category_post_index_path(category) %></li>
  <% end %>
</ul>

<%= form_tag(search_post_index_path, :method => "get") do %>
  <%= search_field_tag(:term, nil, :placeholder => "Search") %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><% if content_for(:title).present? %><%= yield(:title) %> &mdash; NewAperio<% else %>NewAperio &mdash; Web and Mobile Engineering in Baton Rouge, Louisiana<% end %></title>
  <meta name="description" content="NewAperio is a web, iPhone, iPad, iOS, Android, Apple Watch, and Android Wear app development and design collective in Baton Rouge, Louisiana. We're a group of web and mobile entrepreneurs and engineers who love creating magnificient apps for our clients.">
  <meta name="author" content="NewAperio">
	<meta name="keywords" content="web app, web development, app, app development, engineer, entrepreneur, iPhone, iPad, iOS, Android, Apple Watch, Android Wear" />

  <meta name="viewport" content="width=device-width,initial-scale=1">

	<%= auto_discovery_link_tag :atom, feed_post_index_url("atom") %>
	<%= auto_discovery_link_tag :rss, feed_post_index_url("rss") %>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "modernizr" %>
  <%= csrf_meta_tag %>
</head>

<body>

  <div id="container">
    <header id="head" class="clearfix">
			<h1 id="logo"><a href="/" title="NewAperio" class="ir">NewAperio</a></h1>
			<nav role="header">
				<a href="/about" title="About NewAperio" id="nav_about" class="ir">About</a>
				<a href="/portfolio" title="NewAperio's Portfolio" id="nav_portfolio" class="ir">Portfolio</a>
				<a href="/blog" title="NewAperio Blog" id="nav_blog" class="ir">Blog</a>
				<a href="/contact" title="Contact NewAperio" id="nav_contact" class="ir">Contact</a>
			</nav>
    </header>
    <div id="main" role="main" class="clearfix">
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
		<%= yield %>
    </div>
    <div class="push"></div>
  </div> <!--! end of #container -->

  <footer class="clearfix">
		<div id="footercontent">
			<nav role="footer">
				<a href="/about" title="About NewAperio">about</a>
				<a href="/portfolio" title="NewAperio's Portfolio">portfolio</a>
				<a href="/blog" title="NewAperio Blog" id="nav_blog">blog</a>
				<a href="/contact" title="Contact NewAperio" id="nav_contact">contact</a>
			</nav>
			<address>
				<p>&copy;NewAperio, LLC</p>
				<a href="mailto:hello@newaperio.com">hello@newaperio.com</a>
				<p>225/366.9277</p>
			</address>
		</div>
  </footer>

  <%= javascript_include_tag "application" %>

  <%= render :partial => 'layouts/ga' if Rails.env.production? %>

  <!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
</body>
</html>

app/views/layouts/comments.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><% if content_for(:title).present? %><%= yield(:title) %> &mdash; NewAperio<% else %>NewAperio &mdash; Web and Mobile Engineering in Baton Rouge, Louisiana<% end %></title>
  <meta name="description" content="NewAperio is a web, iPhone, iPad, iOS, Android and Blackberry app development and design collective in Baton Rouge, Louisiana. We're a group of web and mobile entrepreneurs and engineers who love creating magnificient apps for our clients.">
  <meta name="author" content="NewAperio">
	<meta name="keywords" content="web app, web development, app, app development, engineer, entrepreneur, iPhone, iPad, iOS, Android, Blackberry" />

  <meta name="viewport" content="width=device-width,initial-scale=1">

	<%= auto_discovery_link_tag :atom, feed_post_index_url("atom") %>
	<%= auto_discovery_link_tag :rss, feed_post_index_url("rss") %>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "modernizr" %>
  <%= csrf_meta_tag %>	
</head>

<body>

  <div id="container">
    <header id="head" class="clearfix">
			<h1 id="logo"><a href="/" title="NewAperio" class="ir">NewAperio</a></h1>
			<nav role="header">
				<a href="/about" title="About NewAperio" id="nav_about" class="ir">About</a>
				<a href="/portfolio" title="NewAperio's Portfolio" id="nav_portfolio" class="ir">Portfolio</a>				
				<a href="/blog" title="NewAperio Blog" id="nav_blog" class="ir">Blog</a>
				<a href="/contact" title="Contact NewAperio" id="nav_contact" class="ir">Contact</a>
			</nav>
    </header>
    <div id="main" role="main" class="clearfix">
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
		<div id="post">
			<%= yield %>
		</div>
		<div id="sidebar">
			<%= render :partial => "layouts/sidebar" %>
		</div>
    </div>
    <div class="push"></div>
  </div> <!--! end of #container -->

  <footer class="clearfix">
		<div id="footercontent">
			<nav role="footer">
				<a href="/about" title="About NewAperio">about</a>
				<a href="/portfolio" title="NewAperio's Portfolio">portfolio</a>				
				<a href="/blog" title="NewAperio Blog" id="nav_blog">blog</a>
				<a href="/contact" title="Contact NewAperio" id="nav_contact">contact</a>
			</nav>
			<address>
				<p>&copy;2011, NewAperio, LLC</p>
				<a href="mailto:hello@newaperio.com">hello@newaperio.com</a>
				<p>225/328.7022</p>
				<p>From Baton Rouge, with love.</p>
			</address>			
		</div>
  </footer>
  
  <%= javascript_include_tag "application" %>

  <%= render :partial => 'layouts/ga' if Rails.env.production? %>

  <!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
</body>
</html>

app/views/layouts/posts.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><% if content_for(:title).present? %><%= yield(:title) %> &mdash; NewAperio<% else %>NewAperio &mdash; Web and Mobile Engineering in Baton Rouge, Louisiana<% end %></title>
  <meta name="description" content="NewAperio is a web, iPhone, iPad, iOS, Android and Blackberry app development and design collective in Baton Rouge, Louisiana. We're a group of web and mobile entrepreneurs and engineers who love creating magnificient apps for our clients.">
  <meta name="author" content="NewAperio">
	<meta name="keywords" content="web app, web development, app, app development, engineer, entrepreneur, iPhone, iPad, iOS, Android, Blackberry" />

  <meta name="viewport" content="width=device-width,initial-scale=1">

	<%= auto_discovery_link_tag :atom, feed_post_index_url("atom") %>
	<%= auto_discovery_link_tag :rss, feed_post_index_url("rss") %>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "modernizr" %>
  <%= csrf_meta_tag %>	
</head>

<body>

  <div id="container">
    <header id="head" class="clearfix">
			<h1 id="logo"><a href="/" title="NewAperio" class="ir">NewAperio</a></h1>
			<nav role="header">
				<a href="/about" title="About NewAperio" id="nav_about" class="ir">About</a>
				<a href="/portfolio" title="NewAperio's Portfolio" id="nav_portfolio" class="ir">Portfolio</a>				
				<a href="/blog" title="NewAperio Blog" id="nav_blog" class="ir">Blog</a>
				<a href="/contact" title="Contact NewAperio" id="nav_contact" class="ir">Contact</a>
			</nav>
    </header>
    <div id="main" role="main" class="clearfix">
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
		<div id="post">
			<%= yield %>
		</div>
		<div id="sidebar">
			<%= render :partial => "layouts/sidebar" %>
		</div>
    </div>
    <div class="push"></div>
  </div> <!--! end of #container -->

  <footer class="clearfix">
		<div id="footercontent">
			<nav role="footer">
				<a href="/about" title="About NewAperio">about</a>
				<a href="/portfolio" title="NewAperio's Portfolio">portfolio</a>				
				<a href="/blog" title="NewAperio Blog" id="nav_blog">blog</a>
				<a href="/contact" title="Contact NewAperio" id="nav_contact">contact</a>
			</nav>
			<address>
				<p>&copy;2011, NewAperio, LLC</p>
				<a href="mailto:hello@newaperio.com">hello@newaperio.com</a>
				<p>225/328.7022</p>
				<p>From Baton Rouge, with love.</p>
			</address>			
		</div>
  </footer>
  
  <%= javascript_include_tag "application" %>

  <%= render :partial => 'layouts/ga' if Rails.env.production? %>

  <!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
</body>
</html>

app/views/posts/_chat.html.erb
<article <% if single %>id="single" <% end %>class="chat">
	<header>
		<h2><%= link_to post.title, post %></h2>
		<div class="meta">chat on <time datetime="<%= post.updated_at %>" pubdate><%= post.updated_at.to_s(:short) %></time></div>		
	</header>
	<ul>
	<% 
	interlocuters = Array.new
	split = post.content.split("\r\n")
	split.each do |line|
	  this_line = line.rpartition(":")
		interlocuters << this_line[0] unless interlocuters.include?(this_line[0])
		this_interlocuter = interlocuters.index(this_line[0]) %>
		<%= raw "<li><span id='interlocuter_#{this_interlocuter}'>#{this_line[0]}: </span>#{textilize(this_line[2])}</li>" %>
	<% end %>
	</ul>
</article>

app/views/posts/_post.html.erb
<article <% if single %>id="single" <% end %>class="post">
	<header>
		<h2><%= link_to post.title, post %></h2>
		<div class="meta">by <%= post.author.name %> on <time datetime="<%= post.updated_at %>" pubdate><%= post.updated_at.to_s(:short) %></time></div>
	</header>
	<p><%= textilize(post.content) %></p>
</article>

app/views/posts/_video.html.erb
<article <% if single %>id="single" <% end %>class="post">
	<header>
		<h2><%= link_to post.title, post %></h2>
		<div class="meta">by <%= post.author.name %> on <time datetime="<%= post.updated_at %>" pubdate><%= post.updated_at.to_s(:short) %></time></div>
	</header>
	<p><%= post.content.html_safe %></p>
</article>

app/views/posts/category.html.erb
<h2><%= pluralize(@posts.count, 'post') %> in <%= @category.name %></h2>

<% for post in @posts %>
<article class="post">
	<header>
		<h2><%= link_to post.title, post %></h2>
		<div class="meta">by <%= post.author.name %> on <time datetime="<%= post.updated_at %>" pubdate><%= post.updated_at.to_s(:short) %></time></div>
	</header>
	<p><%= textilize(post.content) %></p>
</article>
<% end %>

<%= paginate @posts %>

app/views/posts/index.html.erb
<% for post in @posts %>
<%= render_post_type post %>
<% end %>

<%= paginate @posts %>

app/views/posts/search.html.erb
<h2><%= pluralize(@posts.count, 'result') %> for &lsquo;<%= params[:term] %>&rsquo;</h2>

<% for post in @posts %>
<article class="post">
	<header>
		<h2><%= link_to post.title, post %></h2>
		<div class="meta">by <%= post.author.name %> on <time datetime="<%= post.updated_at %>" pubdate><%= post.updated_at.to_s(:short) %></time></div>
	</header>
	<p><%= textilize(post.content) %></p>
</article>
<% end %>

<%= paginate @posts %>

app/views/posts/show.html.erb
<% title @post.title %>
<%= render_post_type @post, false %>